### ISSUE TITLE
Could not start server

### ISSUE THREAD

**Issue by anton-malakhov** [MagicStack/vmbench#13]
```
[19:12:45 fxsatlin01 vmbench] (master)$ ./run_benchmarks --benchmarks tcpecho-uvloop-protocol,tcpecho-uvloop-sockets
TCP echo server (uvloop)
========================

Starting server...
  docker run --rm -t -p 25000:25000 -e UID=10710547 -e GID=22002 -v /localdisk/work/amalakho/vmbench/.cache:/var/lib/cache -v /localdisk/work/amalakho/vmbench/sockets:/tmp/sockets --name magicbench magic/benchmark vex bench python /usr/src/servers/asyncioecho.py --addr=0.0.0.0:25000 --proto --uvloop
Trying to connect to server at address 127.0.0.1:25000
Could not start server
----------------------
Traceback (most recent call last):
  File "/usr/src/servers/asyncioecho.py", line 4, in <module>
    import uvloop
  File "/usr/local/python-venvs/bench/lib/python3.5/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop, Future
  File "uvloop/includes/stdlib.pxi", line 31, in init uvloop.loop (uvloop/loop.c:108082)
AttributeError: module 'asyncio.base_events' has no attribute '_check_resolved_address'

```

**Comment by anton-malakhov** [comment]
Meanwhile `./run_benchmarks --benchmarks tcpecho-golang-sockets` works well, thanks!
